pollapp/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.QuestionList.as_view(),name = 'index'),
    path('<int:pk>/',views.QuestionDetail.as_view(),name='detail'),
    path('<int:pk>/results/',views.Result.as_view(),name ='results'),
    path('<int:question_id>/vote/',views.vote,name='vote')
]

core/models.py
from email.policy import default
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django .views import generic
from .models import *

# Create your views here.\

class QuestionList(generic.ListView):
    queryset = Question.objects.all()
    template_name = 'index.html'

class QuestionDetail(generic.DetailView):
    model = Question
    template_name = 'question_detail.html'

class Result(generic.DetailView):
    model = Question
    template_name = 'results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse('results', args=(question.id,)))

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Polls</title>
    <link rel="stylesheet" href="{% static 'polls.css' %}">
</head>

<body>
    <nav>
        <div class="nav">
            {% comment %} <div class="logo">UNIQ</div> {% endcomment %}
            <div><img src="{% static 'logo.png' %}" alt="" height="30px" width="30px"></div>
            <div class="nav-li">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="">About</a></li>
                <li><a href="">Contact</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            </div>
        </div>
    </nav>
<header>
    <h3>UNIC POLLS APP</h3>
</header>

    {% block content %}

    {% endblock content %}

</body>

</html>

core/templates/index.html
{% extends 'base.html' %}


{% block content %}
<div>
    <ul class="polls">
        {% for question in question_list %}

        <li><a href="{% url 'detail' question.id %}">{{question.question_text}}?</a></li>

        {% endfor %}
    </ul>
</div>
{% endblock content %}

core/templates/question_detail.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'vote' question.id %}" method="post">
    {% csrf_token %}
    <div>
        <fieldset>
            <legend>
                <h2>{{question.question_text}}?</h2>
            </legend>

            {% if error_message %}
            <p style="color: red;">
                <strong> {{error_message}} </strong>
            </p>
            {% endif %}

            {% for choice in question.choice_set.all %}
            <div>
                <input type="radio" name="choice" id="{{choice.id}}" value="{{choice.id}}">
                <label for="{{choice.id}}">{{choice}}</label>
            </div>
            {% endfor %}
            <button type="submit">Vote</button>
        </fieldset>
    </div>
</form>

{% endblock content %}

core/templates/results.html
{% extends 'base.html' %}

{% block content %}
<h2>{{question.question_text}}?</h2>
    
    {% for choice in question.choice_set.all %}
        <li>{{choice}} &rarr; {{choice.votes}} vote{{choice.votes | pluralize}}</li>
    {% endfor %}
    <a href="{% url 'detail' question.id %}"> Vote Again?</a>
        
{% endblock content %}
    